export default () => ({
  port: parseInt(process.env.PORT ?? '', 10) || 8000,
  databaseUrl: process.env.DATABASE_URL ?? process.env.DATABASE_URL_UNPOOLED,
  accessTokenSecret: process.env.ACCESS_TOKEN_SECRET,
  accessTokenExpiresIn: process.env.ACCESS_TOKEN_EXPIRES_IN ?? '30d',
  smtpHost: process.env.SMTP_HOST,
  smtpPort: parseInt(process.env.SMTP_PORT ?? '', 10) || 587,
  smtpUser: process.env.SMTP_USER,
  smtpPassword: process.env.SMTP_PASSWORD,
  smtpSecure: process.env.SMTP_SECURE === 'true',
  smtpMaxConnections: parseInt(process.env.SMTP_MAX_CONNECTIONS ?? '', 10) || 5,
  smtpMaxMessages: parseInt(process.env.SMTP_MAX_MESSAGES ?? '', 10) || 100,
  idsBaseUrl: process.env.IDS_BASE_URL,
  idsUsername: process.env.IDS_USERNAME,
  idsPassword: process.env.IDS_PASSWORD,
  rpcTimeoutMs: parseInt(process.env.RPC_TIMEOUT_MS ?? '', 10) || 30_000,
  idsTimeoutMs: parseInt(process.env.IDS_TIMEOUT_MS ?? '', 10) || 20_000,
  dbQueryTimeoutMs: parseInt(process.env.DB_QUERY_TIMEOUT_MS ?? '', 10) || 30_000,
  graphApiTimeoutMs: parseInt(process.env.GRAPH_API_TIMEOUT_MS ?? '', 10) || 15_000,
  puppeteerTimeoutMs: parseInt(process.env.PUPPETEER_TIMEOUT_MS ?? '', 10) || 60_000,
  maxUploadBytes: parseInt(process.env.MAX_UPLOAD_BYTES ?? '', 10) || 10 * 1024 * 1024,
  locationMaxRows: parseInt(process.env.LOCATION_MAX_ROWS ?? '', 10) || 5000,
});
